from datetime import datetime
from typing import Optional

from pydantic import BaseModel


class TrackBase(BaseModel):
    user_id: str
    timestamp: Optional[datetime]
    artid: str
    artname: str
    trackid: str
    trackname: str


class TrackCreate(TrackBase):
    # id will be automatically generated by MongoDB
    pass


class TrackInDB(TrackBase):
    trackid: str

    class Config:
        orm_mode = True


class TrackUpdate(BaseModel):
    timestamp: Optional[datetime] = None
    artid: Optional[str] = None
    artname: Optional[str] = None
    trackid: Optional[str] = None
    trackname: Optional[str] = None


class Track(TrackInDB):
    pass

    class Config:
        orm_mode = True


class TrackOut(Track):
    pass

    class Config:
        orm_mode = True
